### ISSUE TITLE
运行的时候的问题。。

### ISSUE THREAD

**Issue by FadingFool** [SDchao/AutoVScodeCEnvironment#2]
at SevenZip.SevenZipLibraryManager.LoadLibrary(Object user, Enum format)
   at SevenZip.SevenZipExtractor.Init(String archiveFullName)
   at SevenZip.SevenZipExtractor..ctor(String archiveFullName)
   at AutoVScodeCEnvironment.Classes.Operation.StartThread(String projectPath) in E:\VScode\AutoVScodeCEnvironment\AutoVScodeCEnvironment\Classes\Operation.cs:line 56

**Comment by SDchao** [comment]
您好！在AutoVScodeEnvironment.exe的目录下有没有7z.dll？

**Comment by FadingFool** [comment]
> 您好！在AutoVScodeEnvironment.exe的目录下有没有7z.dll？

**Comment by FadingFool** [comment]
已经解决了谢谢
